services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: couples
      POSTGRES_PASSWORD: couples
      POSTGRES_DB: couples
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080