package quizzes

import "errors"

var (
	ErrCategoryAlreadyExists = errors.New("CATEGORY_ALREADY_EXISTS")
	ErrMissingCategoryAttributes = errors.New("MISSING_CATEGORY_ATTRIBUTES")
	ErrCreatingCategory = errors.New("UNABLE_TO_CREATE_CATEGORY")
	ErrInvalidImageType = errors.New("INVALID_IMAGE_TYPE")
	ErrUpdatingCategory = errors.New("UNABLE_TO_UPDATE_CATEGORY")
	ErrCreatingQuiz = errors.New("UNABLE_TO_CREATE_QUIZ")
	ErrCategoryNotFound = errors.New("CATEGORY_NOT_FOUND")
	ErrEmptyQuizName = errors.New("EMPTY_QUIZ_NAME")
	ErrInvalidLanguage = errors.New("INVALID_LANGUAGE")
	ErrUpdatingQuiz = errors.New("UNABLE_TO_UPDATE_QUIZ")
	ErrQuizNotFound = errors.New("QUIZ_NOT_FOUND")
	ErrInvalidQuestionType = errors.New("INVALID_QUESTION_TYPE")
	ErrCreatingQuestion = errors.New("UNABLE_TO_CREATE_QUESTION")
	ErrRetrievingQuiz = errors.New("UNABLE_TO_GET_QUIZ")
	ErrInvalidQuestionOptions = errors.New("INVALID_QUESTION_OPTIONS")
	ErrDeletingCategory = errors.New("UNABLE_TO_DELETE_CATEGORY")
	ErrDeletingQuestion  = errors.New("UNABLE_TO_DELETE_QUESTION")
	ErrDeletingQuiz = errors.New("UNABLE_TO_DELETE_QUIZ")
	ErrQuestionNotFound = errors.New("QUESTION_NOT_FOUND")
	ErrUnathorizedToEditQuiz = errors.New("UNATHORIZED_TO_EDIT_QUIZ")
	ErrCantModifyOptionsOfQuestionWithAnswers = errors.New("CANT_MODIFY_OPTIONS_OF_QUESTION_WITH_ANSWERS")
	ErrUpdatingQuestion = errors.New("UNABLE_TO_UPDATE_QUESTION")
	ErrRetrievingCategories = errors.New("UNABLE_TO_RETRIEVE_CATEGORIES")
	ErrRetrievingQuizzes = errors.New("UNABLE_TO_RETRIEVE_QUIZES")
	ErrUnableToPublish = errors.New("UNABLE_TO_PUBLISH_QUIZ")
	ErrQuizAlreadyPublished = errors.New("QUIZ_ALREADY_PUBLISHED")
)